### ISSUE TITLE
Expanation for generate_batch and other generate_functions.

### ISSUE THREAD

**Issue by Atharva-Phatak** [tingofurro/keep_it_simple#1]
Does generate_batch in model_generator uses greedy decoding ? if so why wasn't greedy decoding implemented in HF used ?

Can you HF greedy decoding instead of generate_batch because I think so generate_batch is doing greedy decoding.

**Comment by tingofurro** [comment]
Hello Atharva,

You are correct that you can use the generation functions available in HF's common utils_generation.
The reason we are using our own implementation is that at the start of the project, HF's version was still under development and all features we needed were not available yet.

An example of how to integrate the models with HF's `generate` function (which can be used for greedy / beam / sampling, etc. ) is available in the model card: https://huggingface.co/philippelaban/keep_it_simple

For training, we recommend using unbiased sampling (no beam, no nucleus).
To generate final simplifications, one can use any decoding strategy.

I hope this helps!

**Comment by mindojune** [comment]
Hello, thank you for your great work! I know it's been a while, but can you briefly explain why you recommend the unbiased sampling strategy for sampling during training? Thank you.

**Comment by tingofurro** [comment]
Great question!
I believe the idea of SCST (and k-SCST) is to compare the model's unbiased average reward with a baseline reward.
Our thought was that in order to compute the average unbiased reward, it was important not to modify the generation procedure away from unbiased generation.
In practical words: if you use beam search (or some kind of filtering) and it removes some model mistakes from generated candidates, then the model will never learn to correct these mistakes itself. Better to have the model generate these mistakes, and then have the model learn through RL not to make these mistakes.

At prediction time, you can then use fancier generation strategies, since there's no need to be unbiased then.

What do you think?

**Comment by mindojune** [comment]
> Great question! I believe the idea of SCST (and k-SCST) is to compare the model's unbiased average reward with a baseline reward. Our thought was that in order to compute the average unbiased reward, it was important not to modify the generation procedure away from unbiased generation. In practical words: if you use beam search (or some kind of filtering) and it removes some model mistakes from generated candidates, then the model will never learn to correct these mistakes itself. Better to have the model generate these mistakes, and then have the model learn through RL not to make these mistakes.
> 
> At prediction time, you can then use fancier generation strategies, since there's no need to be unbiased then.
> 
> What do you think?

Thank you for your response!

I think the explanation makes sense. Do you think that even if one decides to use filtering during inference from the start, he/she still shouldn't use the same filtering strategy? My rationale for doing so (I'm not an expert) would be that, if we use filtering during inference, we want to consider (or rather, want the model to handle) mistakes that are not filtered out, while we don't have to filter out mistakes made from non-filtering?) 

Great work again, thanks!
